docs(demo): increase Meeting Widget viewing area
webex/widgets pull request #122
Opened 2021-09-20 14:14 UTC by CoroDaniel

2021-09-22 10:59 UTC, alinasuciu approved these changes

2021-09-23 04:49 UTC, lalli-flores requested changes
Demo changes shouldn't trigger a release. Please update commit type to `docs`
```
docs(demo): increase Meeting Widget viewing area

2021-09-24 02:26 UTC, lalli-flores approved these changes

2021-09-24 03:15 UTC, merged

2021-09-24 23:43 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/widgets/v/1.14.0)
- [GitHub release](https://github.com/webex/widgets/releases/tag/v1.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: