feat(Readme): document Firefox concurrent microphones issue
webex/widgets pull request #166
Opened 2021-12-07 15:00 UTC by karinasigartau0798

2021-12-08 08:41 UTC, lalli-flores requested changes
Some feedback on rewording.
Two more things:
1. Since this is this specific to meetings widget, this should be on the Meetings widget README, not the general one
2. Please use `docs` as the commit type and not `feat`. This is a doc change and should not generate a new version

2021-12-08 08:41 UTC, lalli-flores commented
Also, please be sure to add descriptions and links to Jira in your PRs as they are a system of record for future use.

2022-01-11 15:16 UTC, cipak approved these changes

2022-01-11 16:36 UTC, merged

2022-01-15 05:32 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.24.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/widgets/v/1.24.0)
- [GitHub release](https://github.com/webex/widgets/releases/tag/v1.24.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: