docs(Readme): add not supported note
webex/widgets pull request #25
Opened 2020-11-05 14:22 UTC by adamweeks

2020-11-05 16:05 UTC, lalli-flores requested changes
I was working my way around the component system repos. Can you follow the same wording as my opened PR?
https://github.com/webex/component-adapter-interfaces/pull/41/commits/73f012d438f580754401abd03a168c8587dca73b

2020-11-20 15:33 UTC, adamweeks commented
Apologies for creating a branch on the main repo, I used the github web editor to do this and forgot it wasn't on my fork.

2020-11-20 19:16 UTC, lalli-flores approved these changes

2020-11-20 19:16 UTC, lalli-flores commented on README.md
> +We love for you to use the Webex Component System and be part of the feedback process!
I actually took your suggestion lol
```suggestion
We would love for you to use the Webex Component System and be part of the feedback process!
```

2020-12-01 22:42 UTC, merged

2021-01-21 22:38 UTC, webex-components-publisher commented
:tada: This PR is included in version 1.3.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@webex/widgets/v/1.3.1)
- [GitHub release](https://github.com/webex/widgets/releases/tag/v1.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: