Eft
webex/widgets pull request #324
Opened 2024-11-20 09:25 UTC by Shreyas281299

2024-11-20 09:30 UTC, Shreyas281299 commented on .circleci/config.yml
> -            - packages/*/node_modules
We have changed the file structure packages will be inside package/**/*
Examples : 
packages/contact-center/node_modules
packages/widgets/node_modules (https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-583602)

2024-11-20 09:31 UTC, Shreyas281299 commented on .circleci/config.yml
> +  unit_tests:
Added unit test step in pipeline. We test tooling first and then cc-widgets.

2024-11-20 09:31 UTC, Shreyas281299 commented on .circleci/config.yml
> +  release_widgets:
This step will only release cc-widgets

2024-11-20 09:32 UTC, Shreyas281299 commented on .circleci/config.yml
> +
By removing the filter we make sure that build step runs on PRs as well.
<img width="1274" alt="Screenshot 2024-11-20 at 2 36 16 PM" src="https://github.com/user-attachments/assets/b2b9f314-55f8-4fb9-920e-139d233523d8">

2024-11-20 09:35 UTC, Shreyas281299 commented on package.json
> +    ]
When we run `yarn run test:tooling' this is what make sure we only run tooling.

2024-11-20 09:36 UTC, Shreyas281299 commented on packages/contact-center/station-login/package.json
> +  ],
This ensures that we only publish the dist and package.json to npmjs

2024-11-20 09:38 UTC, Shreyas281299 commented on packages/contact-center/store/package.json
> +    "passWithNoTests": true
We can remove this when we have tests

2024-11-20 09:43 UTC, Shreyas281299 commented on .circleci/config.yml
> +              only: feat/cc-widgets
This make sure we only release ccwidgets when we push onto feat/cc-widgets branch

2024-11-20 09:43 UTC, Shreyas281299 commented on .releaserc
> +    ],
Leaving this commit to highlight that this part needs to be added once we have added 2 releases onto github.

2024-11-20 12:15 UTC, mkesavan13 requested changes

2024-11-20 12:15 UTC, mkesavan13 commented on tooling/tests/publish.js
> +  test('error occured while writting "stableVersion" key to', () => {
Check typos and write full statement

2024-11-20 16:04 UTC, Shreyas281299 commented on tooling/tests/publish.js
> +  test('error occured while writting "stableVersion" key to', () => {
Updated the statement

2024-11-20 16:04 UTC, Shreyas281299 commented on tooling/src/publish.js
> +      const workspaceName = `@webex/cc-${fileName}`;
Updated the logic to get name from package.json

2024-11-20 16:04 UTC, Shreyas281299 commented on packages/contact-center/user-state/package.json
> +    "passWithNoTests": true
Added

2024-11-20 16:38 UTC, Shreyas281299 commented on packages/contact-center/store/package.json
> +    "passWithNoTests": true
Updated

2024-11-21 05:10 UTC, mkesavan13 approved these changes

2024-11-21 06:15 UTC, Shreyas281299 commented
<img width="1178" alt="Screenshot 2024-11-21 at 11 44 37 AM" src="https://github.com/user-attachments/assets/455a1e82-c271-4164-9071-1fe9f20a201c">

Changed the pipeline to add release on github with the formate `v${version}`.

2024-11-21 06:24 UTC, merged

2024-11-21 06:29 UTC, sreenara commented
:tada: This PR is included in version 1.28.0-wxcc.1 :tada:

The release is available on [GitHub release](https://github.com/webex/widgets/releases/tag/v1.28.0-wxcc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-11-21 12:44 UTC, sreenara commented
:tada: This PR is included in version 1.28.0-ccwidgets.1 :tada:

The release is available on [GitHub release](https://github.com/webex/widgets/releases/tag/v1.28.0-ccwidgets.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-06 10:39 UTC, sreenara commented on package.json
> +    "test:widgets": "yarn workspace @webex/cc-station-login test:unit && yarn workspace @webex/cc-user-state test:unit",
This is a suggestion for improvement. We could use `yarn workspaces foreach` when we'd like to run the same command across different packages

2025-02-05 11:42 UTC, sreenara commented
:tada: This PR is included in version 1.28.0-ccconnectors.1 :tada:

The release is available on [GitHub release](https://github.com/webex/widgets/releases/tag/v1.28.0-ccconnectors.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: